# Generated by Django 5.2.7 on 2025-10-13 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_add_usuario_to_movimento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materials_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="movimento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SAIDA", "Saída"),
                    ("ADICAO", "Adição (inicial)"),
                ],
                max_length=10,
            ),
        ),
    ]
