# Generated by Django 5.2.7 on 2025-10-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_add_usuario_to_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('ADICAO', 'Adição (inicial)')], max_length=10),
        ),
    ]
