# Generated by Django 5.2.7 on 2025-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_movimento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('ADICAO', 'Adição (inicial)'), ('DELETE', 'Delete')], max_length=10),
        ),
    ]
