# Generated by Django 5.2.7 on 2025-10-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_movimento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='stock.material'),
        ),
    ]
