# Generated by Django 5.2.7 on 2025-10-13 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="criado",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="mensagem",
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(default="-", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
