# Generated by Django 5.2.7 on 2025-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_movimento_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('ADICAO', 'Adição'), ('DELETE', 'Delete'), ('EMPRESTIMO', 'Empréstimo')], max_length=12),
        ),
    ]
