# Generated by Django 5.2.7 on 2025-10-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_movimento_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
