# Generated by Django 5.2.7 on 2025-10-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_material_imagem'),
        ('stock', '0006_movimento_data_devolucao_alter_movimento_tipo'),
    ]

    operations = [
    ]
